"""Regenerate krci_testkit/models from pinned CRD/OpenAPI schemas.

Usage: uv run python codegen/generate.py
Generated modules are committed; this script is re-run only when sources.yaml pins change.
"""

import ast
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import httpx
import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "krci_testkit" / "models"
HEADER = "# GENERATED by codegen/generate.py — DO NOT EDIT.\n"


def crd_to_jsonschema(crd_yaml: str, kind: str) -> dict:
    crd = yaml.safe_load(crd_yaml)
    version = crd["spec"]["versions"][0]
    schema = version["schema"]["openAPIV3Schema"]
    schema["title"] = kind
    return schema


# Tekton types with custom JSON marshalling: the swagger declares them as objects,
# but on the wire they are strings/arrays (e.g. ParamValue serializes as its value).
# Generate them as Any so live CRs validate.
SWAGGER_ANY_OVERRIDES = {"v1.ParamValue"}


def swagger_to_jsonschema(swagger_json: str, kind: str) -> dict:
    doc = json.loads(swagger_json)
    defs = doc["definitions"]
    for name in SWAGGER_ANY_OVERRIDES & defs.keys():
        defs[name] = {"description": "custom JSON marshalling — any of string/array/object"}
    root_key = next(k for k in defs if k.endswith(f".{kind}"))
    # Inline the root definition (instead of $ref-ing it) so the generated root
    # class is a plain BaseModel, not a RootModel wrapper.
    schema = {**defs[root_key], "title": kind, "definitions": defs}
    # Dotted definition names (v1.PipelineRun) trip datamodel-codegen's modular-output
    # mode; flatten every $ref (including dangling refs to absent k8s core types,
    # which the generator turns into Any fallbacks) so generation stays single-file.
    text = json.dumps(schema)
    text = re.sub(
        r'"#/definitions/([^"]+)"',
        lambda m: '"#/definitions/' + m.group(1).replace(".", "") + '"',
        text,
    )
    schema = json.loads(text)
    schema["definitions"] = {k.replace(".", ""): v for k, v in schema["definitions"].items()}
    return schema


def stringify_enums(source: str) -> str:
    """Rewrite string-valued `class X(Enum)` to `class X(StrEnum)`.

    datamodel-codegen has no flag for this, and the difference is load-bearing:
    a plain Enum member is NOT equal to its own value, so test data typed with a
    generated enum could not be compared against (or logged as) the platform
    string it represents — which is the whole reason to use the generated enum in
    test data instead of a hand-written Literal copy. Only classes whose members
    are all string constants are converted, so a future int-valued CRD enum is
    left alone."""
    tree = ast.parse(source)
    targets = {
        node.name
        for node in ast.walk(tree)
        if isinstance(node, ast.ClassDef)
        and [b.id for b in node.bases if isinstance(b, ast.Name)] == ["Enum"]
        and node.body
        and all(
            isinstance(stmt, ast.Assign)
            and isinstance(stmt.value, ast.Constant)
            and isinstance(stmt.value.value, str)
            for stmt in node.body
        )
    }
    if not targets:
        return source
    for name in targets:
        source = source.replace(f"class {name}(Enum):", f"class {name}(StrEnum):")
    return source.replace("from enum import Enum", "from enum import Enum, StrEnum", 1)


def generate(entry: dict) -> None:
    body = httpx.get(entry["url"], follow_redirects=True, timeout=60).raise_for_status().text
    if entry["type"] == "crd":
        schema = crd_to_jsonschema(body, entry["kind"])
    else:
        schema = swagger_to_jsonschema(body, entry["kind"])
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as tmp:
        json.dump(schema, tmp)
        tmp_path = tmp.name
    out_file = OUT / f"{entry['module']}.py"
    subprocess.run(
        [
            "datamodel-codegen",
            "--input",
            tmp_path,
            "--input-file-type",
            "jsonschema",
            "--output",
            str(out_file),
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--class-name",
            entry["kind"],
            "--use-union-operator",
            "--use-standard-collections",
            # Emit Field(default=X) rather than Field(X): pyright only recognises the
            # KEYWORD form as a default, so with positional defaults every optional CR
            # field reads as required at the call site and specs cannot be built from
            # the models at all.
            "--use-default-kwarg",
            "--disable-timestamp",
        ],
        check=True,
    )
    out_file.write_text(HEADER + stringify_enums(out_file.read_text()))
    print(f"generated {out_file}")


def main() -> int:
    sources = yaml.safe_load((ROOT / "codegen" / "sources.yaml").read_text())
    for entry in sources["schemas"]:
        generate(entry)
    return 0


if __name__ == "__main__":
    sys.exit(main())
