"""Regenerate krci_testkit/models from pinned CRD/OpenAPI schemas.

Usage: uv run python codegen/generate.py
Generated modules are committed; this script is re-run only when sources.yaml pins change.
"""

import ast
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import httpx
import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "krci_testkit" / "models"
HEADER = "# GENERATED by codegen/generate.py — DO NOT EDIT.\n"


def crd_to_jsonschema(crd_yaml: str, kind: str, api_version: str) -> dict:
    """The schema of the CRD version named by the entry's api_version.

    The version is selected by name, never by position: a CRD serving several
    versions lists them in an arbitrary order, so taking the first would silently
    generate a different API than the one the suite talks to."""
    crd = yaml.safe_load(crd_yaml)
    wanted = api_version.rpartition("/")[2]
    versions = {v["name"]: v for v in crd["spec"]["versions"]}
    if wanted not in versions:
        raise SystemExit(
            f"{kind}: CRD has no version {wanted!r} (serves {sorted(versions)}) — "
            f"fix api_version or the pinned url in codegen/sources.yaml"
        )
    schema = versions[wanted]["schema"]["openAPIV3Schema"]
    schema["title"] = kind
    if "spec" in schema.get("properties", {}):
        # controller-gen writes the Go field as `json:"spec,omitempty"`, so spec never
        # reaches the CRD's required list — yet every object served by the apiserver
        # carries one. Left optional, the generated model types spec as `Spec | None`
        # and every read of a spec field needs its own narrowing assert.
        schema["required"] = sorted({*schema.get("required", []), "spec"})
    return schema


# Tekton types with custom JSON marshalling: the swagger declares them as objects,
# but on the wire they are strings/arrays (e.g. ParamValue serializes as its value).
# Generate them as Any so live CRs validate.
SWAGGER_ANY_OVERRIDES = {"v1.ParamValue"}


def swagger_to_jsonschema(swagger_json: str, kind: str) -> dict:
    doc = json.loads(swagger_json)
    defs = doc["definitions"]
    for name in SWAGGER_ANY_OVERRIDES & defs.keys():
        defs[name] = {"description": "custom JSON marshalling — any of string/array/object"}
    root_key = next(k for k in defs if k.endswith(f".{kind}"))
    # Inline the root definition (instead of $ref-ing it) so the generated root
    # class is a plain BaseModel, not a RootModel wrapper.
    schema = {**defs[root_key], "title": kind, "definitions": defs}
    # Dotted definition names (v1.PipelineRun) trip datamodel-codegen's modular-output
    # mode; flatten every $ref (including dangling refs to absent k8s core types,
    # which the generator turns into Any fallbacks) so generation stays single-file.
    text = json.dumps(schema)
    text = re.sub(
        r'"#/definitions/([^"]+)"',
        lambda m: '"#/definitions/' + m.group(1).replace(".", "") + '"',
        text,
    )
    schema = json.loads(text)
    schema["definitions"] = {k.replace(".", ""): v for k, v in schema["definitions"].items()}
    return schema


def stringify_enums(source: str) -> str:
    """Rewrite string-valued `class X(Enum)` to `class X(StrEnum)`.

    datamodel-codegen has no flag for this, and the difference is load-bearing:
    a plain Enum member is NOT equal to its own value, so test data typed with a
    generated enum could not be compared against (or logged as) the platform
    string it represents — which is the whole reason to use the generated enum in
    test data instead of a hand-written Literal copy. Only classes whose members
    are all string constants are converted, so a future int-valued CRD enum is
    left alone."""
    tree = ast.parse(source)
    targets = {
        node.name
        for node in ast.walk(tree)
        if isinstance(node, ast.ClassDef)
        and [b.id for b in node.bases if isinstance(b, ast.Name)] == ["Enum"]
        and node.body
        and all(
            isinstance(stmt, ast.Assign)
            and isinstance(stmt.value, ast.Constant)
            and isinstance(stmt.value.value, str)
            for stmt in node.body
        )
    }
    if not targets:
        return source
    for name in targets:
        source = source.replace(f"class {name}(Enum):", f"class {name}(StrEnum):")
    return source.replace("from enum import Enum", "from enum import Enum, StrEnum", 1)


def _default_node(value: ast.expr) -> ast.Constant | None:
    """The field's default, when it is a literal other than None."""
    if isinstance(value, ast.Call):
        if not (isinstance(value.func, ast.Name) and value.func.id == "Field"):
            return None
        value = next((kw.value for kw in value.keywords if kw.arg == "default"), ast.Constant(None))
    if isinstance(value, ast.Constant) and value.value is not None:
        return value
    return None


def _enum_members(tree: ast.Module) -> dict[str, dict[str, str]]:
    """{enum class: {member value: member name}} for the module's string enums."""
    members = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        if not any(isinstance(b, ast.Name) and b.id in ("Enum", "StrEnum") for b in node.bases):
            continue
        members[node.name] = {
            stmt.value.value: stmt.targets[0].id
            for stmt in node.body
            if isinstance(stmt, ast.Assign)
            and isinstance(stmt.targets[0], ast.Name)
            and isinstance(stmt.value, ast.Constant)
            and isinstance(stmt.value.value, str)
        }
    return members


def drop_defaulted_optionals(source: str) -> str:
    """Narrow `X | None = Field(default=<value>)` to `X = Field(default=<value>)`.

    A CRD field carrying a kubebuilder default is absent from the required list —
    it may be omitted on write — but the apiserver fills it in, so it is always
    present on read. datamodel-codegen sees only "not required" and widens the
    annotation to `| None`, which then costs a narrowing assert at every read even
    though the value can never be null. The default itself is kept, so the spec
    builders may still omit the field.

    An enum field's default is also restated as the member (`GitProvider.github`
    rather than `'github'`): pydantic does not validate defaults, so the raw string
    would reach an unset field as a plain str and break the `.value` the narrowed
    annotation now promises."""
    tree = ast.parse(source)
    enums = _enum_members(tree)
    starts = [0]
    for line in source.splitlines(keepends=True):
        starts.append(starts[-1] + len(line))

    def span(node: ast.expr) -> tuple[int, int]:
        assert node.end_lineno is not None
        assert node.end_col_offset is not None
        return (
            starts[node.lineno - 1] + node.col_offset,
            starts[node.end_lineno - 1] + node.end_col_offset,
        )

    edits = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.AnnAssign) or node.value is None:
            continue
        annotation = node.annotation
        default = _default_node(node.value)
        if not (
            default is not None
            and isinstance(annotation, ast.BinOp)
            and isinstance(annotation.op, ast.BitOr)
            and isinstance(annotation.right, ast.Constant)
            and annotation.right.value is None
        ):
            continue
        inner = ast.get_source_segment(source, annotation.left)
        assert inner is not None
        edits.append((*span(annotation), inner))
        member = enums.get(inner, {}).get(default.value) if isinstance(default.value, str) else None
        if member is not None:
            edits.append((*span(default), f"{inner}.{member}"))
    for start, end, replacement in sorted(edits, reverse=True):
        source = source[:start] + replacement + source[end:]
    return source


def generate(entry: dict) -> None:
    body = httpx.get(entry["url"], follow_redirects=True, timeout=60).raise_for_status().text
    is_crd = entry["type"] == "crd"
    if is_crd:
        schema = crd_to_jsonschema(body, entry["kind"], entry["api_version"])
    else:
        schema = swagger_to_jsonschema(body, entry["kind"])
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as tmp:
        json.dump(schema, tmp)
        tmp_path = tmp.name
    out_file = OUT / f"{entry['module']}.py"
    subprocess.run(
        [
            "datamodel-codegen",
            "--input",
            tmp_path,
            "--input-file-type",
            "jsonschema",
            "--output",
            str(out_file),
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--class-name",
            entry["kind"],
            "--use-union-operator",
            "--use-standard-collections",
            # Emit Field(default=X) rather than Field(X): pyright only recognises the
            # KEYWORD form as a default, so with positional defaults every optional CR
            # field reads as required at the call site and specs cannot be built from
            # the models at all.
            "--use-default-kwarg",
            "--disable-timestamp",
        ],
        check=True,
    )
    # The banner names the temp file the schema was staged in, so it differs on every
    # run and would make the committed models look changed when they are not.
    source = re.sub(r"^#   filename:.*\n", "", out_file.read_text(), count=1, flags=re.MULTILINE)
    source = stringify_enums(source)
    # Only CRDs: kubebuilder defaults are applied by the apiserver on write. The Tekton
    # swagger carries Go zero-value defaults that no server ever fills in.
    if is_crd:
        source = drop_defaulted_optionals(source)
    out_file.write_text(HEADER + source)
    print(f"generated {out_file}")


def main() -> int:
    sources = yaml.safe_load((ROOT / "codegen" / "sources.yaml").read_text())
    for entry in sources["schemas"]:
        generate(entry)
    return 0


if __name__ == "__main__":
    sys.exit(main())
