# GENERATED by codegen/generate.py — DO NOT EDIT.
# generated by datamodel-codegen:

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, constr


class Spec(BaseModel):
    applications: list[str] = Field(
        ..., description='A list of applications included in CDPipeline.', min_length=1
    )
    applicationsToPromote: list[str] | None = Field(
        default=None,
        description='A list of applications which will promote after successful release.',
    )
    deploymentType: str = Field(
        ..., description='Type of workload to be deployed, e.g., container, custom.'
    )
    description: str | None = Field(
        default=None,
        description='Description of CD pipeline.',
        examples=['This is a CD pipeline for deploying applications'],
    )
    inputDockerStreams: list[str] = Field(
        ..., description='A list of docker streams', min_length=1
    )
    name: constr(min_length=2) = Field(..., description='Name of CD pipeline')


class Result(StrEnum):
    success = 'success'
    error = 'error'


class Status(BaseModel):
    action: str = Field(..., description='The last Action was performed.')
    available: bool = Field(
        ...,
        description='This flag indicates neither CDPipeline are initialized and ready to work. Defaults to false.',
    )
    detailed_message: str | None = Field(
        default=None,
        description='Detailed information regarding action result\nwhich were performed',
    )
    last_time_updated: AwareDatetime = Field(
        ..., description='Information when the last time the action were performed.'
    )
    result: Result = Field(
        ...,
        description='A result of an action which were performed.\n- "success": action where performed successfully;\n- "error": error has occurred;',
    )
    status: str = Field(..., description='Specifies a current status of CDPipeline.')
    username: str = Field(..., description='Name of user who made a last change.')
    value: str = Field(..., description='Specifies a current state of CDPipeline.')


class CDPipeline(BaseModel):
    apiVersion: str | None = Field(
        default=None,
        description='APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources',
    )
    kind: str | None = Field(
        default=None,
        description='Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds',
    )
    metadata: dict[str, Any] | None = None
    spec: Spec = Field(
        ..., description='CDPipelineSpec defines the desired state of CDPipeline.'
    )
    status: Status | None = Field(
        default=None,
        description='CDPipelineStatus defines the observed state of CDPipeline.',
    )
