# GENERATED by codegen/generate.py — DO NOT EDIT.
# generated by datamodel-codegen:
#   filename:  tmpymnkww9c.json

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, conint, constr


class Spec(BaseModel):
    branchName: str = Field(..., description='Name of a branch.')
    codebaseName: str = Field(..., description='Name of Codebase associated with.')
    fromCommit: str | None = Field(
        default=None,
        description='FromCommit is a commit hash or branch name.\nThe new branch will be created starting from the selected commit hash or branch name.\nIf a branch name is provided, the new branch will be created from the latest commit of that branch.',
    )
    pipelines: dict[str, str] | None = Field(
        default=None,
        description='Pipelines is a map of pipelines related to the branch.',
        examples=[
            {
                'build': 'build-pipeline',
                'review': 'review-pipeline',
                'security': 'security-pipeline',
            }
        ],
    )
    release: bool = Field(
        ..., description='Flag if branch is used as "release" branch.'
    )
    version: str | None = Field(
        default=None,
        description='Version of the branch. It\'s required for versioning type "semver".',
    )


class Status1(StrEnum):
    True_ = 'True'
    False_ = 'False'
    Unknown = 'Unknown'


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime = Field(
        ...,
        description='lastTransitionTime is the last time the condition transitioned from one status to another.\nThis should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.',
    )
    message: constr(max_length=32768) = Field(
        ...,
        description='message is a human readable message indicating details about the transition.\nThis may be an empty string.',
    )
    observedGeneration: conint(ge=0) | None = Field(
        default=None,
        description='observedGeneration represents the .metadata.generation that the condition was set based upon.\nFor instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date\nwith respect to the current state of the instance.',
    )
    reason: constr(
        pattern=r'^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$',
        min_length=1,
        max_length=1024,
    ) = Field(
        ...,
        description="reason contains a programmatic identifier indicating the reason for the condition's last transition.\nProducers of specific condition types may define expected values and meanings for this field,\nand whether the values are considered a guaranteed API.\nThe value should be a CamelCase string.\nThis field may not be empty.",
    )
    status: Status1 = Field(
        ..., description='status of the condition, one of True, False, Unknown.'
    )
    type: constr(
        pattern=r'^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$',
        max_length=316,
    ) = Field(
        ...,
        description='type of condition in CamelCase or in foo.example.com/CamelCase.',
    )


class Result(StrEnum):
    success = 'success'
    error = 'error'


class Status(BaseModel):
    action: str = Field(..., description='The last Action was performed.')
    build: str | None = None
    conditions: list[Condition] | None = Field(
        default=None,
        description="Conditions represent the latest available observations of an object's state.\nEach condition type is an independent observation (e.g. Stale); new types can be\nadded over time without schema changes.",
    )
    detailedMessage: str | None = Field(
        default=None,
        description='Detailed information regarding action result\nwhich were performed',
    )
    failureCount: int = Field(
        ..., description='Amount of times, operator fail to serve with existing CR.'
    )
    git: str | None = Field(
        default=None, description='Specifies a status of action for git.'
    )
    lastSuccessfulBuild: str | None = None
    lastTimeUpdated: AwareDatetime = Field(
        ..., description='Information when the last time the action were performed.'
    )
    result: Result = Field(
        ...,
        description='A result of an action which were performed.\n- "success": action where performed successfully;\n- "error": error has occurred;',
    )
    status: str = Field(
        ..., description='Specifies a current status of CodebaseBranch.'
    )
    username: str = Field(..., description='Name of user who made a last change.')
    value: str = Field(..., description='Specifies a current state of CodebaseBranch.')
    versionHistory: list[str] | None = None


class CodebaseBranch(BaseModel):
    apiVersion: str | None = Field(
        default=None,
        description='APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources',
    )
    kind: str | None = Field(
        default=None,
        description='Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds',
    )
    metadata: dict[str, Any] | None = None
    spec: Spec | None = Field(
        default=None,
        description='CodebaseBranchSpec defines the desired state of CodebaseBranch.',
    )
    status: Status | None = Field(
        default=None,
        description='CodebaseBranchStatus defines the observed state of CodebaseBranch.',
    )
