# GENERATED by codegen/generate.py — DO NOT EDIT.
# generated by datamodel-codegen:

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class Tag(BaseModel):
    created: str
    digest: str | None = None
    name: str


class Spec(BaseModel):
    codebase: str = Field(..., description='Name of Codebase associated with.')
    imageName: str = Field(
        ...,
        description='Docker container name without tag, e.g. registry-name/path/name.',
    )
    tags: list[Tag] | None = Field(
        default=None,
        description='A list of docker image tags available for ImageName and their creation date.',
    )


class Status(BaseModel):
    detailed_message: str | None = Field(
        default=None,
        description='Detailed information regarding action result\nwhich were performed',
    )
    failureCount: int = Field(
        ..., description='Amount of times, operator fail to serve with existing CR.'
    )


class CodebaseImageStream(BaseModel):
    apiVersion: str | None = Field(
        default=None,
        description='APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources',
    )
    kind: str | None = Field(
        default=None,
        description='Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds',
    )
    metadata: dict[str, Any] | None = None
    spec: Spec = Field(
        ...,
        description='CodebaseImageStreamSpec defines the desired state of CodebaseImageStream.',
    )
    status: Status | None = Field(
        default=None,
        description='CodebaseImageStreamStatus defines the observed state of CodebaseImageStream.',
    )
