# GENERATED by codegen/generate.py — DO NOT EDIT.
# generated by datamodel-codegen:
#   filename:  tmpal9thv2t.json

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field


class CiTool(StrEnum):
    tekton = 'tekton'
    gitlab = 'gitlab'


class SecretRef(BaseModel):
    name: str | None = Field(
        default='',
        description='Name of the referent.\nThis field is effectively required, but due to backwards compatibility is\nallowed to be empty. Instances of this type with an empty value here are\nalmost certainly wrong.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names',
    )


class CloneRepositoryCredentials(BaseModel):
    clearSecretAfterUse: bool | None = Field(
        default=True,
        description='ClearSecretAfterUse indicates whether the secret should be deleted after use.\nFor backward compatibility, the default value is true.',
    )
    secretRef: SecretRef = Field(
        ...,
        description='SecretRef is a reference to secret that contains credentials for cloning repository.\nThe secret must contain "username" and "password" keys.',
    )


class Repository(BaseModel):
    url: str


class Strategy(StrEnum):
    create = 'create'
    clone = 'clone'
    import_ = 'import'


class Versioning(BaseModel):
    startFrom: str | None = Field(
        default=None,
        description='StartFrom is required when versioning type is not default.',
    )
    type: str


class Spec(BaseModel):
    branchToCopyInDefaultBranch: str | None = Field(
        default=None,
        description='While we clone new codebase we can select specific branch to clone.\nSelected branch will become a default branch for a new codebase (e.g. master, main).',
    )
    buildTool: str = Field(..., description='A build tool which is used on codebase.')
    ciTool: CiTool | None = Field(
        default='tekton', description='A name of tool which should be used as CI.'
    )
    cloneRepositoryCredentials: CloneRepositoryCredentials | None = Field(
        default=None,
        description='CloneRepositoryCredentials contains reference to secret with credentials used to clone repository.',
    )
    commitMessagePattern: str | None = None
    defaultBranch: str = Field(..., description='Name of default branch.')
    deploymentScript: str | None = 'helm-chart'
    description: str | None = Field(
        default=None, description='A short description of codebase.'
    )
    disablePutDeployTemplates: bool | None = Field(
        default=None,
        description='Controller must skip step "put deploy templates" in action chain.',
    )
    emptyProject: bool = Field(
        ...,
        description='A flag indicating how project should be provisioned. Default: false',
    )
    framework: str = Field(..., description='A framework used in codebase.')
    gitServer: str = Field(
        ...,
        description='A name of git server which will be used as VCS.\nExample: "gerrit".',
    )
    gitUrlPath: str = Field(
        ...,
        description='A relative path for git repository. Should start from /. Example: /company/api-app.',
    )
    jiraIssueMetadataPayload: str | None = None
    jiraServer: str | None = None
    lang: str = Field(..., description='Programming language used in codebase.')
    private: bool | None = Field(
        default=True,
        description='Private indicates if we need to create private repository.',
    )
    repository: Repository | None = None
    strategy: Strategy = Field(
        ..., description='integration strategy for a codebase, e.g. clone, import, etc.'
    )
    testReportFramework: str | None = None
    ticketNamePattern: str | None = None
    type: str = Field(
        ..., description='Type of codebase. E.g. application, autotest or library.'
    )
    versioning: Versioning


class Result(StrEnum):
    success = 'success'
    error = 'error'


class Status(BaseModel):
    action: str = Field(..., description='The last Action was performed.')
    available: bool = Field(
        ...,
        description='This flag indicates neither Codebase are initialized and ready to work. Defaults to false.',
    )
    detailedMessage: str | None = Field(
        default=None,
        description='Detailed information regarding action result\nwhich were performed',
    )
    failureCount: int = Field(
        ..., description='Amount of times, operator fail to serve with existing CR.'
    )
    git: str = Field(..., description='Specifies a status of action for git.')
    gitWebUrl: str | None = Field(
        default=None, description='Stores GitWebUrl of codebase.'
    )
    lastTimeUpdated: AwareDatetime = Field(
        ..., description='Information when the last time the action were performed.'
    )
    result: Result = Field(
        ...,
        description='A result of an action which were performed.\n- "success": action where performed successfully;\n- "error": error has occurred;',
    )
    status: str = Field(..., description='Specifies a current status of Codebase.')
    username: str = Field(..., description='Name of user who made a last change.')
    value: str = Field(..., description='Specifies a current state of Codebase.')
    webHookID: int | None = Field(
        default=None,
        description='Stores ID of webhook which was created for a codebase.\nDeprecated: Because the webhook id can be more than just an integer. Use WebHookRef instead.',
    )
    webHookRef: str | None = Field(
        default=None,
        description='WebHookRef stores unique reference to webhook which was created for a codebase.',
    )


class Codebase(BaseModel):
    apiVersion: str | None = Field(
        default=None,
        description='APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources',
    )
    kind: str | None = Field(
        default=None,
        description='Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds',
    )
    metadata: dict[str, Any] | None = None
    spec: Spec | None = Field(
        default=None, description='CodebaseSpec defines the desired state of Codebase.'
    )
    status: Status | None = Field(
        default=None,
        description='CodebaseStatus defines the observed state of Codebase.',
    )
