# GENERATED by codegen/generate.py — DO NOT EDIT.
# generated by datamodel-codegen:
#   filename:  tmp2sfpjku4.json

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any

from pydantic import BaseModel, Field


class GitProvider(StrEnum):
    gerrit = 'gerrit'
    gitlab = 'gitlab'
    github = 'github'
    bitbucket = 'bitbucket'


class Spec(BaseModel):
    gitHost: str
    gitProvider: GitProvider | None = Field(
        default='github',
        description='GitProvider is a git provider type. It can be gerrit, github or gitlab. Default value is gerrit.',
    )
    gitUser: str | None = Field(
        default='git', description='GitUser is a user name for git server.'
    )
    httpsPort: int
    nameSshKeySecret: str = Field(
        ...,
        description="NameSshKeySecret is the name of the Kubernetes secret containing Git repository credentials.\nRequired keys:\n  - token: Git provider access token (required)\nOptional keys:\n  - id_rsa: SSH private key for Git operations over SSH\n  - secretString: Webhook secret for validating webhook requests\n  - username: Git username to override the default GitUser\nFor Gerrit provider, only id_rsa key is required and used.\nWhen id_rsa is present the operator connects over SSH and verifies the server's\nhost key against the operator's ssh-known-hosts ConfigMap; hosts other than\ngithub.com, gitlab.com and bitbucket.org must be added there first.",
        examples=['my-git-credentials'],
    )
    skipWebhookSSLVerification: bool | None = Field(
        default=None,
        description='SkipWebhookSSLVerification is a flag to skip webhook tls verification.',
    )
    sshPort: int
    tektonDisabled: bool | None = Field(
        default=None,
        description="TektonDisabled disables creation of Tekton EventListener and associated\nIngress/Route resources for this GitServer.\nUse this when the git provider's native CI (e.g. GitLab CI, GitHub Actions)\nis used instead of Tekton, or when webhook endpoints are managed externally.",
    )
    webhookUrl: str | None = Field(
        default=None,
        description='WebhookUrl is a URL for webhook that will be created in the git provider.\nIf not set, a new EventListener and Ingress will be created and used for webhooks.',
        examples=['https://webhook-url.com'],
    )


class Status(BaseModel):
    connected: bool | None = Field(
        default=None,
        description='Connected shows if operator is connected to git server.',
    )
    error: str | None = Field(
        default=None,
        description='Error represents error message if something went wrong.',
    )
    status: str | None = Field(
        default=None,
        description='Status indicates the current status of the GitServer.\nPossible values are: ok, failed.',
    )


class GitServer(BaseModel):
    apiVersion: str | None = Field(
        default=None,
        description='APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources',
    )
    kind: str | None = Field(
        default=None,
        description='Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds',
    )
    metadata: dict[str, Any] | None = None
    spec: Spec | None = Field(
        default=None,
        description='GitServerSpec defines the desired state of GitServer.',
    )
    status: Status | None = Field(
        default=None,
        description='GitServerStatus defines the observed state of GitServer.',
    )
