# GENERATED by codegen/generate.py — DO NOT EDIT.
# generated by datamodel-codegen:

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, RootModel


class V1ArtifactValue(BaseModel):
    digest: dict[str, str] | None = None
    uri: str | None = Field(
        default=None,
        description='Algorithm-specific digests for verifying the content (e.g., SHA256)',
    )


class V1ParamValue(RootModel[Any]):
    root: Any = Field(
        ..., description='custom JSON marshalling — any of string/array/object'
    )


class V1PipelineRef(BaseModel):
    apiVersion: str | None = Field(
        default=None, description='API version of the referent'
    )
    name: str | None = Field(
        default=None,
        description='Name of the referent; More info: http://kubernetes.io/docs/user-guide/identifiers#names',
    )


class V1PipelineResult(BaseModel):
    description: str | None = Field(
        default='',
        description='Description is a human-readable description of the result',
    )
    name: str = Field(..., description='Name the given name')
    type: str | None = Field(
        default=None,
        description="Type is the user-specified type of the result. The possible types are 'string', 'array', and 'object', with 'string' as the default. 'array' and 'object' types are alpha features.",
    )
    value: V1ParamValue = Field(
        ..., description='Value the expression used to retrieve the value'
    )


class V1PipelineRunResult(BaseModel):
    name: str = Field(
        ..., description="Name is the result's name as declared by the Pipeline"
    )
    value: V1ParamValue = Field(
        ...,
        description='Value is the result returned from the execution of this PipelineRun',
    )


class V1PipelineTaskMetadata(BaseModel):
    annotations: dict[str, str] | None = None
    labels: dict[str, str] | None = None


class V1PipelineTaskParam(BaseModel):
    name: str
    value: str


class V1PipelineTaskRun(BaseModel):
    name: str | None = None


class V1PipelineWorkspaceDeclaration(BaseModel):
    description: str | None = Field(
        default=None,
        description='Description is a human readable string describing how the workspace will be used in the Pipeline. It can be useful to include a bit of detail about which tasks are intended to have access to the data on the workspace.',
    )
    name: str = Field(
        ...,
        description='Name is the name of a workspace to be provided by a PipelineRun.',
    )
    optional: bool | None = Field(
        default=None,
        description='Optional marks a Workspace as not being required in PipelineRuns. By default this field is false and so declared workspaces are required.',
    )


class V1PropertySpec(BaseModel):
    type: str | None = None


class V1Ref(BaseModel):
    name: str | None = Field(default=None, description='Name of the referenced step')


class V1RefSource(BaseModel):
    digest: dict[str, str] | None = Field(
        default=None,
        description='Digest is a collection of cryptographic digests for the contents of the artifact specified by URI. Example: {"sha1": "f99d13e554ffcb696dee719fa85b695cb5b0f428"}',
    )
    entryPoint: str | None = Field(
        default=None,
        description='EntryPoint identifies the entry point into the build. This is often a path to a build definition file and/or a target label within that file. Example: "task/git-clone/0.10/git-clone.yaml"',
    )
    uri: str | None = Field(
        default=None,
        description='URI indicates the identity of the source of the build definition. Example: "https://github.com/tektoncd/catalog"',
    )


class V1ResultRef(BaseModel):
    pipelineTask: str
    property: str
    result: str
    resultsIndex: int


class V1StepOutputConfig(BaseModel):
    path: str | None = Field(
        default=None,
        description="Path to duplicate stdout stream to on container's local filesystem.",
    )


class V1StepResult(BaseModel):
    description: str | None = Field(
        default=None,
        description='Description is a human-readable description of the result',
    )
    name: str = Field(..., description='Name the given name')
    properties: dict[str, V1PropertySpec] | None = Field(
        default=None,
        description='Properties is the JSON Schema properties to support key-value pairs results.',
    )
    type: str | None = Field(
        default=None,
        description="The possible types are 'string', 'array', and 'object', with 'string' as the default.",
    )


class V1TaskBreakpoints(BaseModel):
    beforeSteps: list[str] | None = None
    onFailure: str | None = Field(
        default=None,
        description='if enabled, pause TaskRun on failure of a step failed step will not exit',
    )


class V1TaskRef(BaseModel):
    apiVersion: str | None = Field(
        default=None,
        description='API version of the referent Note: A Task with non-empty APIVersion and Kind is considered a Custom Task',
    )
    kind: str | None = Field(
        default=None,
        description='TaskKind indicates the Kind of the Task: 1. Namespaced Task when Kind is set to "Task". If Kind is "", it defaults to "Task". 2. Custom Task when Kind is non-empty and APIVersion is non-empty',
    )
    name: str | None = Field(
        default=None,
        description='Name of the referent; More info: http://kubernetes.io/docs/user-guide/identifiers#names',
    )


class V1TaskResult(BaseModel):
    description: str | None = Field(
        default=None,
        description='Description is a human-readable description of the result',
    )
    name: str = Field(..., description='Name the given name')
    properties: dict[str, V1PropertySpec] | None = Field(
        default=None,
        description='Properties is the JSON Schema properties to support key-value pairs results.',
    )
    type: str | None = Field(
        default=None,
        description='Type is the user-specified type of the result. The possible type is currently "string" and will support "array" in following work.',
    )
    value: V1ParamValue | None = Field(
        default=None,
        description='Value the expression used to retrieve the value of the result from an underlying Step.',
    )


class V1TaskRunDebug(BaseModel):
    breakpoints: V1TaskBreakpoints | None = None


class V1TaskRunResult(BaseModel):
    name: str = Field(..., description='Name the given name')
    type: str | None = Field(
        default=None,
        description='Type is the user-specified type of the result. The possible type is currently "string" and will support "array" in following work.',
    )
    value: V1ParamValue = Field(..., description='Value the given value of the result')


class V1WhenExpression(BaseModel):
    cel: str | None = Field(
        default=None,
        description='CEL is a string of Common Language Expression, which can be used to conditionally execute the task based on the result of the expression evaluation More info about CEL syntax: https://github.com/google/cel-spec/blob/master/doc/langdef.md',
    )
    input: str | None = Field(
        default=None,
        description='Input is the string for guard checking which can be a static input or an output from a parent Task',
    )
    operator: str | None = Field(
        default=None,
        description="Operator that represents an Input's relationship to the values",
    )
    values: list[str] | None = Field(
        default=None,
        description='Values is an array of strings, which is compared against the input, for guard checking It must be non-empty',
    )


class V1WorkspaceDeclaration(BaseModel):
    description: str | None = Field(
        default=None,
        description='Description is an optional human readable description of this volume.',
    )
    mountPath: str | None = Field(
        default=None,
        description='MountPath overrides the directory that the volume will be made available at.',
    )
    name: str = Field(
        ..., description='Name is the name by which you can bind the volume at runtime.'
    )
    optional: bool | None = Field(
        default=None,
        description='Optional marks a Workspace as not being required in TaskRuns. By default this field is false and so declared workspaces are required.',
    )
    readOnly: bool | None = Field(
        default=None,
        description='ReadOnly dictates whether a mounted volume is writable. By default this field is false and so mounted volumes are writable.',
    )


class V1WorkspacePipelineTaskBinding(BaseModel):
    name: str = Field(
        ..., description='Name is the name of the workspace as declared by the task'
    )
    subPath: str | None = Field(
        default=None,
        description='SubPath is optionally a directory on the volume which should be used for this binding (i.e. the volume will be mounted at this sub directory).',
    )
    workspace: str | None = Field(
        default=None,
        description='Workspace is the name of the workspace declared by the pipeline',
    )


class V1WorkspaceUsage(BaseModel):
    mountPath: str = Field(
        ...,
        description="MountPath is the path that the workspace should be mounted to inside the Step or Sidecar, overriding any MountPath specified in the Task's WorkspaceDeclaration.",
    )
    name: str = Field(
        ...,
        description='Name is the name of the workspace this Step or Sidecar wants access to.',
    )


class GithubcomtektoncdpipelinepkgapisconfigFeatureFlags(RootModel[Any]):
    root: Any


class Githubcomtektoncdpipelinepkgapisrunv1beta1CustomRunStatus(RootModel[Any]):
    root: Any


class K8sioapimachinerypkgruntimeRawExtension(RootModel[Any]):
    root: Any


class KnativeCondition(RootModel[Any]):
    root: Any


class V1Affinity(RootModel[Any]):
    root: Any


class V1CSIVolumeSource(RootModel[Any]):
    root: Any


class V1ConfigMapVolumeSource(RootModel[Any]):
    root: Any


class V1ContainerPort(RootModel[Any]):
    root: Any


class V1ContainerStateRunning(RootModel[Any]):
    root: Any


class V1ContainerStateTerminated(RootModel[Any]):
    root: Any


class V1ContainerStateWaiting(RootModel[Any]):
    root: Any


class V1Duration(RootModel[Any]):
    root: Any


class V1EmptyDirVolumeSource(RootModel[Any]):
    root: Any


class V1EnvFromSource(RootModel[Any]):
    root: Any


class V1EnvVar(RootModel[Any]):
    root: Any


class V1HostAlias(RootModel[Any]):
    root: Any


class V1Lifecycle(RootModel[Any]):
    root: Any


class V1ListMeta(RootModel[Any]):
    root: Any


class V1LocalObjectReference(RootModel[Any]):
    root: Any


class V1ObjectMeta(RootModel[Any]):
    root: Any


class V1PersistentVolumeClaim(RootModel[Any]):
    root: Any


class V1PersistentVolumeClaimVolumeSource(RootModel[Any]):
    root: Any


class V1PodDNSConfig(RootModel[Any]):
    root: Any


class V1PodSecurityContext(RootModel[Any]):
    root: Any


class V1Probe(RootModel[Any]):
    root: Any


class V1ProjectedVolumeSource(RootModel[Any]):
    root: Any


class V1ResourceRequirements(RootModel[Any]):
    root: Any


class V1SecretVolumeSource(RootModel[Any]):
    root: Any


class V1SecurityContext(RootModel[Any]):
    root: Any


class V1Time(RootModel[Any]):
    root: Any


class V1Toleration(RootModel[Any]):
    root: Any


class V1TopologySpreadConstraint(RootModel[Any]):
    root: Any


class V1Volume(RootModel[Any]):
    root: Any


class V1VolumeDevice(RootModel[Any]):
    root: Any


class V1VolumeMount(RootModel[Any]):
    root: Any


class PodAffinityAssistantTemplate(BaseModel):
    imagePullSecrets: list[V1LocalObjectReference] | None = Field(
        default=None,
        description='ImagePullSecrets gives the name of the secret used by the pod to pull the image if specified',
    )
    nodeSelector: dict[str, str] | None = Field(
        default=None,
        description="NodeSelector is a selector which must be true for the pod to fit on a node. Selector which must match a node's labels for the pod to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/",
    )
    priorityClassName: str | None = Field(
        default=None,
        description='If specified, indicates the pod\'s priority. "system-node-critical" and "system-cluster-critical" are two special keywords which indicate the highest priorities with the former being the highest priority. Any other name must be defined by creating a PriorityClass object with that name. If not specified, the pod priority will be default or zero if there is no default.',
    )
    securityContext: V1PodSecurityContext | None = Field(
        default=None,
        description='SecurityContext sets the security context for the pod',
    )
    tolerations: list[V1Toleration] | None = Field(
        default=None, description="If specified, the pod's tolerations."
    )


class PodTemplate(BaseModel):
    affinity: V1Affinity | None = Field(
        default=None,
        description="If specified, the pod's scheduling constraints. See Pod.spec.affinity (API version: v1)",
    )
    automountServiceAccountToken: bool | None = Field(
        default=None,
        description='AutomountServiceAccountToken indicates whether pods running as this service account should have an API token automatically mounted.',
    )
    dnsConfig: V1PodDNSConfig | None = Field(
        default=None,
        description='Specifies the DNS parameters of a pod. Parameters specified here will be merged to the generated DNS configuration based on DNSPolicy.',
    )
    dnsPolicy: str | None = Field(
        default=None,
        description='Set DNS policy for the pod. Defaults to "ClusterFirst". Valid values are \'ClusterFirst\', \'Default\' or \'None\'. DNS parameters given in DNSConfig will be merged with the policy selected with DNSPolicy.',
    )
    enableServiceLinks: bool | None = Field(
        default=None,
        description="EnableServiceLinks indicates whether information about services should be injected into pod's environment variables, matching the syntax of Docker links. Optional: Defaults to true.",
    )
    env: list[V1EnvVar] | None = Field(
        default=None,
        description='List of environment variables that can be provided to the containers belonging to the pod.',
    )
    hostAliases: list[V1HostAlias] | None = Field(
        default=None,
        description="HostAliases is an optional list of hosts and IPs that will be injected into the pod's hosts file if specified. This is only valid for non-hostNetwork pods.",
    )
    hostNetwork: bool | None = Field(
        default=None,
        description='HostNetwork specifies whether the pod may use the node network namespace',
    )
    hostUsers: bool | None = Field(
        default=None,
        description="HostUsers indicates whether the pod will use the host's user namespace. Optional: Default to true. If set to true or not present, the pod will be run in the host user namespace, useful for when the pod needs a feature only available to the host user namespace, such as loading a kernel module with CAP_SYS_MODULE. When set to false, a new user namespace is created for the pod. Setting false is useful to mitigating container breakout vulnerabilities such as allowing containers to run as root without their user having root privileges on the host. This field depends on the kubernetes feature gate UserNamespacesSupport being enabled.",
    )
    imagePullSecrets: list[V1LocalObjectReference] | None = Field(
        default=None,
        description='ImagePullSecrets gives the name of the secret used by the pod to pull the image if specified',
    )
    nodeSelector: dict[str, str] | None = Field(
        default=None,
        description="NodeSelector is a selector which must be true for the pod to fit on a node. Selector which must match a node's labels for the pod to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/",
    )
    priorityClassName: str | None = Field(
        default=None,
        description='If specified, indicates the pod\'s priority. "system-node-critical" and "system-cluster-critical" are two special keywords which indicate the highest priorities with the former being the highest priority. Any other name must be defined by creating a PriorityClass object with that name. If not specified, the pod priority will be default or zero if there is no default.',
    )
    runtimeClassName: str | None = Field(
        default=None,
        description='RuntimeClassName refers to a RuntimeClass object in the node.k8s.io group, which should be used to run this pod. If no RuntimeClass resource matches the named class, the pod will not be run. If unset or empty, the "legacy" RuntimeClass will be used, which is an implicit class with an empty definition that uses the default runtime handler. More info: https://git.k8s.io/enhancements/keps/sig-node/runtime-class.md This is a beta feature as of Kubernetes v1.14.',
    )
    schedulerName: str | None = Field(
        default=None,
        description='SchedulerName specifies the scheduler to be used to dispatch the Pod',
    )
    securityContext: V1PodSecurityContext | None = Field(
        default=None,
        description='SecurityContext holds pod-level security attributes and common container settings. Optional: Defaults to empty.  See type description for default values of each field. See Pod.spec.securityContext (API version: v1)',
    )
    tolerations: list[V1Toleration] | None = Field(
        default=None, description="If specified, the pod's tolerations."
    )
    topologySpreadConstraints: list[V1TopologySpreadConstraint] | None = Field(
        default=None,
        description='TopologySpreadConstraints controls how Pods are spread across your cluster among failure-domains such as regions, zones, nodes, and other user-defined topology domains.',
    )
    volumes: list[V1Volume] | None = Field(
        default=None,
        description='List of volumes that can be mounted by containers belonging to the pod. More info: https://kubernetes.io/docs/concepts/storage/volumes See Pod.spec.volumes (API version: v1)',
    )


class V1Artifact(BaseModel):
    buildOutput: bool | None = Field(
        default=None,
        description='Indicate if the artifact is a build output or a by-product',
    )
    name: str | None = Field(
        default=None, description="The artifact's identifying category name"
    )
    values: list[V1ArtifactValue] | None = Field(
        default=None, description='A collection of values related to the artifact'
    )


class V1Artifacts(BaseModel):
    inputs: list[V1Artifact] | None = None
    outputs: list[V1Artifact] | None = None


class V1ChildStatusReference(BaseModel):
    apiVersion: str | None = None
    displayName: str | None = Field(
        default=None,
        description='DisplayName is a user-facing name of the pipelineTask that may be used to populate a UI.',
    )
    kind: str | None = None
    name: str | None = Field(
        default=None,
        description='Name is the name of the TaskRun or Run this is referencing.',
    )
    pipelineTaskName: str | None = Field(
        default=None,
        description='PipelineTaskName is the name of the PipelineTask this is referencing.',
    )
    whenExpressions: list[V1WhenExpression] | None = Field(
        default=None,
        description='WhenExpressions is the list of checks guarding the execution of the PipelineTask',
    )


class V1Param(BaseModel):
    name: str
    value: V1ParamValue


class V1ParamSpec(BaseModel):
    default: V1ParamValue | None = Field(
        default=None,
        description='Default is the value a parameter takes if no input value is supplied. If default is set, a Task may be executed without a supplied value for the parameter.',
    )
    description: str | None = Field(
        default=None,
        description='Description is a user-facing description of the parameter that may be used to populate a UI.',
    )
    enum: list[str] | None = Field(
        default=None,
        description='Enum declares a set of allowed param input values for tasks/pipelines that can be validated. If Enum is not set, no input validation is performed for the param.',
    )
    name: str = Field(
        ..., description='Name declares the name by which a parameter is referenced.'
    )
    properties: dict[str, V1PropertySpec] | None = Field(
        default=None,
        description='Properties is the JSON Schema properties to support key-value pairs parameter.',
    )
    type: str | None = Field(
        default=None,
        description='Type is the user-specified type of the parameter. The possible types are currently "string", "array" and "object", and "string" is the default.',
    )


class V1PipelineRunRunStatus(BaseModel):
    pipelineTaskName: str | None = Field(
        default=None, description='PipelineTaskName is the name of the PipelineTask.'
    )
    status: Githubcomtektoncdpipelinepkgapisrunv1beta1CustomRunStatus | None = Field(
        default=None, description='Status is the RunStatus for the corresponding Run'
    )
    whenExpressions: list[V1WhenExpression] | None = Field(
        default=None,
        description='WhenExpressions is the list of checks guarding the execution of the PipelineTask',
    )


class V1PipelineTaskRunTemplate(BaseModel):
    podTemplate: PodTemplate | None = None
    serviceAccountName: str | None = None


class V1Provenance(BaseModel):
    featureFlags: GithubcomtektoncdpipelinepkgapisconfigFeatureFlags | None = Field(
        default=None,
        description='FeatureFlags identifies the feature flags that were used during the task/pipeline run',
    )
    refSource: V1RefSource | None = Field(
        default=None,
        description='RefSource identifies the source where a remote task/pipeline came from.',
    )


class V1ResolverRef(BaseModel):
    params: list[V1Param] | None = Field(
        default=None,
        description='Params contains the parameters used to identify the referenced Tekton resource. Example entries might include "repo" or "path" but the set of params ultimately depends on the chosen resolver.',
    )
    resolver: str | None = Field(
        default=None,
        description='Resolver is the name of the resolver that should perform resolution of the referenced Tekton resource, such as "git".',
    )


class V1Sidecar(BaseModel):
    args: list[str] | None = Field(
        default=None,
        description='Arguments to the entrypoint. The image\'s CMD is used if this is not provided. Variable references $(VAR_NAME) are expanded using the Sidecar\'s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. "$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell',
    )
    command: list[str] | None = Field(
        default=None,
        description='Entrypoint array. Not executed within a shell. The image\'s ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the Sidecar\'s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. "$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell',
    )
    computeResources: V1ResourceRequirements | None = Field(
        default={},
        description='ComputeResources required by this Sidecar. Cannot be updated. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/',
        validate_default=True,
    )
    env: list[V1EnvVar] | None = Field(
        default=None,
        description='List of environment variables to set in the Sidecar. Cannot be updated.',
    )
    envFrom: list[V1EnvFromSource] | None = Field(
        default=None,
        description='List of sources to populate environment variables in the Sidecar. The keys defined within a source must be a C_IDENTIFIER. All invalid keys will be reported as an event when the container is starting. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence. Cannot be updated.',
    )
    image: str | None = Field(
        default=None,
        description='Image reference name. More info: https://kubernetes.io/docs/concepts/containers/images',
    )
    imagePullPolicy: str | None = Field(
        default=None,
        description='Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images',
    )
    lifecycle: V1Lifecycle | None = Field(
        default=None,
        description='Actions that the management system should take in response to Sidecar lifecycle events. Cannot be updated.',
    )
    livenessProbe: V1Probe | None = Field(
        default=None,
        description='Periodic probe of Sidecar liveness. Container will be restarted if the probe fails. Cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes',
    )
    name: str = Field(
        ...,
        description='Name of the Sidecar specified as a DNS_LABEL. Each Sidecar in a Task must have a unique name (DNS_LABEL). Cannot be updated.',
    )
    ports: list[V1ContainerPort] | None = Field(
        default=None,
        description='List of ports to expose from the Sidecar. Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default "0.0.0.0" address inside a container will be accessible from the network. Cannot be updated.',
    )
    readinessProbe: V1Probe | None = Field(
        default=None,
        description='Periodic probe of Sidecar service readiness. Container will be removed from service endpoints if the probe fails. Cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes',
    )
    restartPolicy: str | None = Field(
        default=None,
        description='RestartPolicy refers to kubernetes RestartPolicy. It can only be set for an initContainer and must have it\'s policy set to "Always". It is currently left optional to help support Kubernetes versions prior to 1.29 when this feature was introduced.',
    )
    script: str | None = Field(
        default=None,
        description='Script is the contents of an executable file to execute.\n\nIf Script is not empty, the Step cannot have an Command or Args.',
    )
    securityContext: V1SecurityContext | None = Field(
        default=None,
        description='SecurityContext defines the security options the Sidecar should be run with. If set, the fields of SecurityContext override the equivalent fields of PodSecurityContext. More info: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/',
    )
    startupProbe: V1Probe | None = Field(
        default=None,
        description="StartupProbe indicates that the Pod the Sidecar is running in has successfully initialized. If specified, no other probes are executed until this completes successfully. If this probe fails, the Pod will be restarted, just as if the livenessProbe failed. This can be used to provide different probe parameters at the beginning of a Pod's lifecycle, when it might take a long time to load data or warm a cache, than during steady-state operation. This cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes",
    )
    stdin: bool | None = Field(
        default=None,
        description='Whether this Sidecar should allocate a buffer for stdin in the container runtime. If this is not set, reads from stdin in the Sidecar will always result in EOF. Default is false.',
    )
    stdinOnce: bool | None = Field(
        default=None,
        description='Whether the container runtime should close the stdin channel after it has been opened by a single attach. When stdin is true the stdin stream will remain open across multiple attach sessions. If stdinOnce is set to true, stdin is opened on Sidecar start, is empty until the first client attaches to stdin, and then remains open and accepts data until the client disconnects, at which time stdin is closed and remains closed until the Sidecar is restarted. If this flag is false, a container processes that reads from stdin will never receive an EOF. Default is false',
    )
    terminationMessagePath: str | None = Field(
        default=None,
        description="Optional: Path at which the file to which the Sidecar's termination message will be written is mounted into the Sidecar's filesystem. Message written is intended to be brief final status, such as an assertion failure message. Will be truncated by the node if greater than 4096 bytes. The total message length across all containers will be limited to 12kb. Defaults to /dev/termination-log. Cannot be updated.",
    )
    terminationMessagePolicy: str | None = Field(
        default=None,
        description='Indicate how the termination message should be populated. File will use the contents of terminationMessagePath to populate the Sidecar status message on both success and failure. FallbackToLogsOnError will use the last chunk of Sidecar log output if the termination message file is empty and the Sidecar exited with an error. The log output is limited to 2048 bytes or 80 lines, whichever is smaller. Defaults to File. Cannot be updated.',
    )
    tty: bool | None = Field(
        default=None,
        description="Whether this Sidecar should allocate a TTY for itself, also requires 'stdin' to be true. Default is false.",
    )
    volumeDevices: list[V1VolumeDevice] | None = Field(
        default=None,
        description='volumeDevices is the list of block devices to be used by the Sidecar.',
    )
    volumeMounts: list[V1VolumeMount] | None = Field(
        default=None,
        description="Volumes to mount into the Sidecar's filesystem. Cannot be updated.",
    )
    workingDir: str | None = Field(
        default=None,
        description="Sidecar's working directory. If not specified, the container runtime's default will be used, which might be configured in the container image. Cannot be updated.",
    )
    workspaces: list[V1WorkspaceUsage] | None = Field(
        default=None,
        description='This is an alpha field. You must set the "enable-api-fields" feature flag to "alpha" for this field to be supported.\n\nWorkspaces is a list of workspaces from the Task that this Sidecar wants exclusive access to. Adding a workspace to this list means that any other Step or Sidecar that does not also request this Workspace will not have access to it.',
    )


class V1SidecarState(BaseModel):
    container: str | None = None
    imageID: str | None = None
    name: str | None = None
    running: V1ContainerStateRunning | None = Field(
        default=None, description='Details about a running container'
    )
    terminated: V1ContainerStateTerminated | None = Field(
        default=None, description='Details about a terminated container'
    )
    waiting: V1ContainerStateWaiting | None = Field(
        default=None, description='Details about a waiting container'
    )


class V1SkippedTask(BaseModel):
    name: str = Field(..., description='Name is the Pipeline Task name')
    reason: str = Field(
        ..., description='Reason is the cause of the PipelineTask being skipped.'
    )
    whenExpressions: list[V1WhenExpression] | None = Field(
        default=None,
        description='WhenExpressions is the list of checks guarding the execution of the PipelineTask',
    )


class V1Step(BaseModel):
    args: list[str] | None = Field(
        default=None,
        description='Arguments to the entrypoint. The image\'s CMD is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container\'s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. "$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell',
    )
    command: list[str] | None = Field(
        default=None,
        description='Entrypoint array. Not executed within a shell. The image\'s ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container\'s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. "$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell',
    )
    computeResources: V1ResourceRequirements | None = Field(
        default={},
        description='ComputeResources required by this Step. Cannot be updated. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/',
        validate_default=True,
    )
    displayName: str | None = Field(
        default=None,
        description='DisplayName is a user-facing name of the step that may be used to populate a UI.',
    )
    env: list[V1EnvVar] | None = Field(
        default=None,
        description='List of environment variables to set in the Step. Cannot be updated.',
    )
    envFrom: list[V1EnvFromSource] | None = Field(
        default=None,
        description='List of sources to populate environment variables in the Step. The keys defined within a source must be a C_IDENTIFIER. All invalid keys will be reported as an event when the Step is starting. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence. Cannot be updated.',
    )
    image: str | None = Field(
        default=None,
        description='Docker image name. More info: https://kubernetes.io/docs/concepts/containers/images',
    )
    imagePullPolicy: str | None = Field(
        default=None,
        description='Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images',
    )
    name: str = Field(
        ...,
        description='Name of the Step specified as a DNS_LABEL. Each Step in a Task must have a unique name.',
    )
    onError: str | None = Field(
        default=None,
        description='OnError defines the exiting behavior of a container on error can be set to [ continue | stopAndFail ]',
    )
    params: list[V1Param] | None = Field(
        default=None,
        description='Params declares parameters passed to this step action.',
    )
    ref: V1Ref | None = Field(
        default=None, description='Contains the reference to an existing StepAction.'
    )
    results: list[V1StepResult] | None = Field(
        default=None,
        description='Results declares StepResults produced by the Step.\n\nIt can be used in an inlined Step when used to store Results to $(step.results.resultName.path). It cannot be used when referencing StepActions using [v1.Step.Ref]. The Results declared by the StepActions will be stored here instead.',
    )
    script: str | None = Field(
        default=None,
        description='Script is the contents of an executable file to execute.\n\nIf Script is not empty, the Step cannot have an Command and the Args will be passed to the Script.',
    )
    securityContext: V1SecurityContext | None = Field(
        default=None,
        description='SecurityContext defines the security options the Step should be run with. If set, the fields of SecurityContext override the equivalent fields of PodSecurityContext. More info: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/',
    )
    stderrConfig: V1StepOutputConfig | None = Field(
        default=None,
        description='Stores configuration for the stderr stream of the step.',
    )
    stdoutConfig: V1StepOutputConfig | None = Field(
        default=None,
        description='Stores configuration for the stdout stream of the step.',
    )
    timeout: V1Duration | None = Field(
        default=None,
        description="Timeout is the time after which the step times out. Defaults to never. Refer to Go's ParseDuration documentation for expected format: https://golang.org/pkg/time/#ParseDuration",
    )
    volumeDevices: list[V1VolumeDevice] | None = Field(
        default=None,
        description='volumeDevices is the list of block devices to be used by the Step.',
    )
    volumeMounts: list[V1VolumeMount] | None = Field(
        default=None,
        description="Volumes to mount into the Step's filesystem. Cannot be updated.",
    )
    when: list[V1WhenExpression] | None = Field(
        default=None,
        description='When is a list of when expressions that need to be true for the task to run',
    )
    workingDir: str | None = Field(
        default=None,
        description="Step's working directory. If not specified, the container runtime's default will be used, which might be configured in the container image. Cannot be updated.",
    )
    workspaces: list[V1WorkspaceUsage] | None = Field(
        default=None,
        description='This is an alpha field. You must set the "enable-api-fields" feature flag to "alpha" for this field to be supported.\n\nWorkspaces is a list of workspaces from the Task that this Step wants exclusive access to. Adding a workspace to this list means that any other Step or Sidecar that does not also request this Workspace will not have access to it.',
    )


class V1StepState(BaseModel):
    container: str | None = None
    imageID: str | None = None
    inputs: list[V1Artifact] | None = None
    name: str | None = None
    outputs: list[V1Artifact] | None = None
    provenance: V1Provenance | None = None
    results: list[V1TaskRunResult] | None = None
    running: V1ContainerStateRunning | None = Field(
        default=None, description='Details about a running container'
    )
    terminated: V1ContainerStateTerminated | None = Field(
        default=None, description='Details about a terminated container'
    )
    terminationReason: str | None = None
    waiting: V1ContainerStateWaiting | None = Field(
        default=None, description='Details about a waiting container'
    )


class V1StepTemplate(BaseModel):
    args: list[str] | None = Field(
        default=None,
        description='Arguments to the entrypoint. The image\'s CMD is used if this is not provided. Variable references $(VAR_NAME) are expanded using the Step\'s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. "$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell',
    )
    command: list[str] | None = Field(
        default=None,
        description='Entrypoint array. Not executed within a shell. The image\'s ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the Step\'s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. "$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell',
    )
    computeResources: V1ResourceRequirements | None = Field(
        default={},
        description='ComputeResources required by this Step. Cannot be updated. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/',
        validate_default=True,
    )
    env: list[V1EnvVar] | None = Field(
        default=None,
        description='List of environment variables to set in the Step. Cannot be updated.',
    )
    envFrom: list[V1EnvFromSource] | None = Field(
        default=None,
        description='List of sources to populate environment variables in the Step. The keys defined within a source must be a C_IDENTIFIER. All invalid keys will be reported as an event when the Step is starting. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence. Cannot be updated.',
    )
    image: str | None = Field(
        default=None,
        description='Image reference name. More info: https://kubernetes.io/docs/concepts/containers/images',
    )
    imagePullPolicy: str | None = Field(
        default=None,
        description='Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images',
    )
    securityContext: V1SecurityContext | None = Field(
        default=None,
        description='SecurityContext defines the security options the Step should be run with. If set, the fields of SecurityContext override the equivalent fields of PodSecurityContext. More info: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/',
    )
    volumeDevices: list[V1VolumeDevice] | None = Field(
        default=None,
        description='volumeDevices is the list of block devices to be used by the Step.',
    )
    volumeMounts: list[V1VolumeMount] | None = Field(
        default=None,
        description="Volumes to mount into the Step's filesystem. Cannot be updated.",
    )
    workingDir: str | None = Field(
        default=None,
        description="Step's working directory. If not specified, the container runtime's default will be used, which might be configured in the container image. Cannot be updated.",
    )


class V1TaskRunInputs(BaseModel):
    params: list[V1Param] | None = None


class V1TaskRunSidecarSpec(BaseModel):
    computeResources: V1ResourceRequirements = Field(
        ..., description='The resource requirements to apply to the Sidecar.'
    )
    name: str = Field(..., description='The name of the Sidecar to override.')


class V1TaskRunStepSpec(BaseModel):
    computeResources: V1ResourceRequirements = Field(
        ..., description='The resource requirements to apply to the Step.'
    )
    name: str = Field(..., description='The name of the Step to override.')


class V1TaskSpec(BaseModel):
    description: str | None = Field(
        default=None,
        description='Description is a user-facing description of the task that may be used to populate a UI.',
    )
    displayName: str | None = Field(
        default=None,
        description='DisplayName is a user-facing name of the task that may be used to populate a UI.',
    )
    params: list[V1ParamSpec] | None = Field(
        default=None,
        description='Params is a list of input parameters required to run the task. Params must be supplied as inputs in TaskRuns unless they declare a default value.',
    )
    results: list[V1TaskResult] | None = Field(
        default=None, description='Results are values that this Task can output'
    )
    sidecars: list[V1Sidecar] | None = Field(
        default=None,
        description="Sidecars are run alongside the Task's step containers. They begin before the steps start and end after the steps complete.",
    )
    stepTemplate: V1StepTemplate | None = Field(
        default=None,
        description='StepTemplate can be used as the basis for all step containers within the Task, so that the steps inherit settings on the base container.',
    )
    steps: list[V1Step] | None = Field(
        default=None,
        description='Steps are the steps of the build; each step is run sequentially with the source mounted into /workspace.',
    )
    volumes: list[V1Volume] | None = Field(
        default=None,
        description='Volumes is a collection of volumes that are available to mount into the steps of the build. See Pod.spec.volumes (API version: v1)',
    )
    workspaces: list[V1WorkspaceDeclaration] | None = Field(
        default=None, description='Workspaces are the volumes that this Task requires.'
    )


class V1TimeoutFields(BaseModel):
    finally_: V1Duration | None = Field(
        default=None,
        alias='finally',
        description="Finally sets the maximum allowed duration of this pipeline's finally",
    )
    pipeline: V1Duration | None = Field(
        default=None,
        description='Pipeline sets the maximum allowed duration for execution of the entire pipeline. The sum of individual timeouts for tasks and finally must not exceed this value.',
    )
    tasks: V1Duration | None = Field(
        default=None,
        description="Tasks sets the maximum allowed duration of this pipeline's tasks",
    )


class V1WorkspaceBinding(BaseModel):
    configMap: V1ConfigMapVolumeSource | None = Field(
        default=None,
        description='ConfigMap represents a configMap that should populate this workspace.',
    )
    csi: V1CSIVolumeSource | None = Field(
        default=None,
        description='CSI (Container Storage Interface) represents ephemeral storage that is handled by certain external CSI drivers.',
    )
    emptyDir: V1EmptyDirVolumeSource | None = Field(
        default=None,
        description="EmptyDir represents a temporary directory that shares a Task's lifetime. More info: https://kubernetes.io/docs/concepts/storage/volumes#emptydir Either this OR PersistentVolumeClaim can be used.",
    )
    name: str = Field(
        ..., description='Name is the name of the workspace populated by the volume.'
    )
    persistentVolumeClaim: V1PersistentVolumeClaimVolumeSource | None = Field(
        default=None,
        description='PersistentVolumeClaimVolumeSource represents a reference to a PersistentVolumeClaim in the same namespace. Either this OR EmptyDir can be used.',
    )
    projected: V1ProjectedVolumeSource | None = Field(
        default=None,
        description='Projected represents a projected volume that should populate this workspace.',
    )
    secret: V1SecretVolumeSource | None = Field(
        default=None,
        description='Secret represents a secret that should populate this workspace.',
    )
    subPath: str | None = Field(
        default=None,
        description='SubPath is optionally a directory on the volume which should be used for this binding (i.e. the volume will be mounted at this sub directory).',
    )
    volumeClaimTemplate: V1PersistentVolumeClaim | None = Field(
        default=None,
        description='VolumeClaimTemplate is a template for a claim that will be created in the same namespace. The PipelineRun controller is responsible for creating a unique claim for each instance of PipelineRun. See PersistentVolumeClaim (API version: v1)',
    )


class V1EmbeddedTask(BaseModel):
    apiVersion: str | None = None
    description: str | None = Field(
        default=None,
        description='Description is a user-facing description of the task that may be used to populate a UI.',
    )
    displayName: str | None = Field(
        default=None,
        description='DisplayName is a user-facing name of the task that may be used to populate a UI.',
    )
    kind: str | None = None
    metadata: V1PipelineTaskMetadata | None = Field(default={}, validate_default=True)
    params: list[V1ParamSpec] | None = Field(
        default=None,
        description='Params is a list of input parameters required to run the task. Params must be supplied as inputs in TaskRuns unless they declare a default value.',
    )
    results: list[V1TaskResult] | None = Field(
        default=None, description='Results are values that this Task can output'
    )
    sidecars: list[V1Sidecar] | None = Field(
        default=None,
        description="Sidecars are run alongside the Task's step containers. They begin before the steps start and end after the steps complete.",
    )
    spec: K8sioapimachinerypkgruntimeRawExtension | None = Field(
        default=None, description='Spec is a specification of a custom task'
    )
    stepTemplate: V1StepTemplate | None = Field(
        default=None,
        description='StepTemplate can be used as the basis for all step containers within the Task, so that the steps inherit settings on the base container.',
    )
    steps: list[V1Step] | None = Field(
        default=None,
        description='Steps are the steps of the build; each step is run sequentially with the source mounted into /workspace.',
    )
    volumes: list[V1Volume] | None = Field(
        default=None,
        description='Volumes is a collection of volumes that are available to mount into the steps of the build. See Pod.spec.volumes (API version: v1)',
    )
    workspaces: list[V1WorkspaceDeclaration] | None = Field(
        default=None, description='Workspaces are the volumes that this Task requires.'
    )


class V1IncludeParams(BaseModel):
    name: str | None = Field(default=None, description='Name the specified combination')
    params: list[V1Param] | None = Field(
        default=None,
        description='Params takes only `Parameters` of type `"string"` The names of the `params` must match the names of the `params` in the underlying `Task`',
    )


class V1Matrix(BaseModel):
    include: list[V1IncludeParams] | None = Field(
        default=None,
        description='Include is a list of IncludeParams which allows passing in specific combinations of Parameters into the Matrix.',
    )
    params: list[V1Param] | None = Field(
        default=None,
        description='Params is a list of parameters used to fan out the pipelineTask Params takes only `Parameters` of type `"array"` Each array element is supplied to the `PipelineTask` by substituting `params` of type `"string"` in the underlying `Task`. The names of the `params` in the `Matrix` must match the names of the `params` in the underlying `Task` that they will be substituting.',
    )


class V1PipelineTaskRunSpec(BaseModel):
    computeResources: V1ResourceRequirements | None = Field(
        default=None, description='Compute resources to use for this TaskRun'
    )
    metadata: V1PipelineTaskMetadata | None = None
    pipelineTaskName: str | None = None
    podTemplate: PodTemplate | None = None
    serviceAccountName: str | None = None
    sidecarSpecs: list[V1TaskRunSidecarSpec] | None = None
    stepSpecs: list[V1TaskRunStepSpec] | None = None
    timeout: V1Duration | None = Field(
        default=None,
        description="Duration after which the TaskRun times out. Overrides the timeout specified on the Task's spec if specified. Takes lower precedence to PipelineRun's `spec.timeouts.tasks` Refer Go's ParseDuration documentation for expected format: https://golang.org/pkg/time/#ParseDuration",
    )


class V1Task(BaseModel):
    apiVersion: str | None = Field(
        default=None,
        description='APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources',
    )
    kind: str | None = Field(
        default=None,
        description='Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds',
    )
    metadata: V1ObjectMeta | None = Field(default={}, validate_default=True)
    spec: V1TaskSpec | None = Field(
        default={},
        description='Spec holds the desired state of the Task from the client',
        validate_default=True,
    )


class V1TaskList(BaseModel):
    apiVersion: str | None = Field(
        default=None,
        description='APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources',
    )
    items: list[V1Task]
    kind: str | None = Field(
        default=None,
        description='Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds',
    )
    metadata: V1ListMeta | None = Field(default={}, validate_default=True)


class V1TaskRunSpec(BaseModel):
    computeResources: V1ResourceRequirements | None = Field(
        default=None, description='Compute resources to use for this TaskRun'
    )
    debug: V1TaskRunDebug | None = None
    managedBy: str | None = Field(
        default=None,
        description='ManagedBy indicates which controller is responsible for reconciling this resource. If unset or set to "tekton.dev/pipeline", the default Tekton controller will manage this resource. This field is immutable.',
    )
    params: list[V1Param] | None = None
    podTemplate: PodTemplate | None = Field(
        default=None, description='PodTemplate holds pod specific configuration'
    )
    retries: int | None = Field(
        default=None,
        description='Retries represents how many times this TaskRun should be retried in the event of task failure.',
    )
    serviceAccountName: str | None = ''
    sidecarSpecs: list[V1TaskRunSidecarSpec] | None = Field(
        default=None,
        description='Specs to apply to Sidecars in this TaskRun. If a field is specified in both a Sidecar and a SidecarSpec, the value from the SidecarSpec will be used. This field is only supported when the alpha feature gate is enabled.',
    )
    status: str | None = Field(
        default=None,
        description='Used for cancelling a TaskRun (and maybe more later on)',
    )
    statusMessage: str | None = Field(
        default=None, description='Status message for cancellation.'
    )
    stepSpecs: list[V1TaskRunStepSpec] | None = Field(
        default=None,
        description='Specs to apply to Steps in this TaskRun. If a field is specified in both a Step and a StepSpec, the value from the StepSpec will be used. This field is only supported when the alpha feature gate is enabled.',
    )
    taskRef: V1TaskRef | None = Field(
        default=None,
        description='no more than one of the TaskRef and TaskSpec may be specified.',
    )
    taskSpec: V1TaskSpec | None = Field(
        default=None,
        description='Specifying TaskSpec can be disabled by setting `disable-inline-spec` feature flag. See Task.spec (API version: tekton.dev/v1)',
    )
    timeout: V1Duration | None = Field(
        default=None,
        description="Time after which one retry attempt times out. Defaults to 1 hour. Refer Go's ParseDuration documentation for expected format: https://golang.org/pkg/time/#ParseDuration",
    )
    workspaces: list[V1WorkspaceBinding] | None = Field(
        default=None,
        description='Workspaces is a list of WorkspaceBindings from volumes to workspaces.',
    )


class V1TaskRunStatus(BaseModel):
    annotations: dict[str, str] | None = Field(
        default=None,
        description='Annotations is additional Status fields for the Resource to save some additional State as well as convey more information to the user. This is roughly akin to Annotations on any k8s resource, just the reconciler conveying richer information outwards.',
    )
    artifacts: V1Artifacts | None = Field(
        default=None,
        description="Artifacts are the list of artifacts written out by the task's containers",
    )
    completionTime: V1Time | None = Field(
        default=None, description='CompletionTime is the time the build completed.'
    )
    conditions: list[KnativeCondition] | None = Field(
        default=None,
        description="Conditions the latest available observations of a resource's current state.",
    )
    observedGeneration: int | None = Field(
        default=None,
        description="ObservedGeneration is the 'Generation' of the Service that was last processed by the controller.",
    )
    podName: str = Field(
        ...,
        description="PodName is the name of the pod responsible for executing this task's steps.",
    )
    provenance: V1Provenance | None = Field(
        default=None,
        description='Provenance contains some key authenticated metadata about how a software artifact was built (what sources, what inputs/outputs, etc.).',
    )
    results: list[V1TaskRunResult] | None = Field(
        default=None,
        description="Results are the list of results written out by the task's containers",
    )
    retriesStatus: list[V1TaskRunStatus] | None = Field(
        default=None,
        description='RetriesStatus contains the history of TaskRunStatus in case of a retry in order to keep record of failures. All TaskRunStatus stored in RetriesStatus will have no date within the RetriesStatus as is redundant.',
    )
    sidecars: list[V1SidecarState] | None = Field(
        default=None,
        description='The list has one entry per sidecar in the manifest. Each entry is represents the imageid of the corresponding sidecar.',
    )
    spanContext: dict[str, str] | None = Field(
        default=None, description='SpanContext contains tracing span context fields'
    )
    startTime: V1Time | None = Field(
        default=None, description='StartTime is the time the build is actually started.'
    )
    steps: list[V1StepState] | None = Field(
        default=None,
        description='Steps describes the state of each build step container.',
    )
    taskSpec: V1TaskSpec | None = Field(
        default=None,
        description='TaskSpec contains the Spec from the dereferenced Task definition used to instantiate this TaskRun.',
    )


class V1TaskRunStatusFields(BaseModel):
    artifacts: V1Artifacts | None = Field(
        default=None,
        description="Artifacts are the list of artifacts written out by the task's containers",
    )
    completionTime: V1Time | None = Field(
        default=None, description='CompletionTime is the time the build completed.'
    )
    podName: str = Field(
        ...,
        description="PodName is the name of the pod responsible for executing this task's steps.",
    )
    provenance: V1Provenance | None = Field(
        default=None,
        description='Provenance contains some key authenticated metadata about how a software artifact was built (what sources, what inputs/outputs, etc.).',
    )
    results: list[V1TaskRunResult] | None = Field(
        default=None,
        description="Results are the list of results written out by the task's containers",
    )
    retriesStatus: list[V1TaskRunStatus] | None = Field(
        default=None,
        description='RetriesStatus contains the history of TaskRunStatus in case of a retry in order to keep record of failures. All TaskRunStatus stored in RetriesStatus will have no date within the RetriesStatus as is redundant.',
    )
    sidecars: list[V1SidecarState] | None = Field(
        default=None,
        description='The list has one entry per sidecar in the manifest. Each entry is represents the imageid of the corresponding sidecar.',
    )
    spanContext: dict[str, str] | None = Field(
        default=None, description='SpanContext contains tracing span context fields'
    )
    startTime: V1Time | None = Field(
        default=None, description='StartTime is the time the build is actually started.'
    )
    steps: list[V1StepState] | None = Field(
        default=None,
        description='Steps describes the state of each build step container.',
    )
    taskSpec: V1TaskSpec | None = Field(
        default=None,
        description='TaskSpec contains the Spec from the dereferenced Task definition used to instantiate this TaskRun.',
    )


class V1PipelineRunTaskRunStatus(BaseModel):
    pipelineTaskName: str | None = Field(
        default=None, description='PipelineTaskName is the name of the PipelineTask.'
    )
    status: V1TaskRunStatus | None = Field(
        default=None,
        description='Status is the TaskRunStatus for the corresponding TaskRun',
    )
    whenExpressions: list[V1WhenExpression] | None = Field(
        default=None,
        description='WhenExpressions is the list of checks guarding the execution of the PipelineTask',
    )


class V1TaskRun(BaseModel):
    apiVersion: str | None = Field(
        default=None,
        description='APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources',
    )
    kind: str | None = Field(
        default=None,
        description='Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds',
    )
    metadata: V1ObjectMeta | None = Field(default={}, validate_default=True)
    spec: V1TaskRunSpec | None = Field(default={}, validate_default=True)
    status: V1TaskRunStatus | None = Field(default={}, validate_default=True)


class V1TaskRunList(BaseModel):
    apiVersion: str | None = Field(
        default=None,
        description='APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources',
    )
    items: list[V1TaskRun]
    kind: str | None = Field(
        default=None,
        description='Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds',
    )
    metadata: V1ListMeta | None = Field(default={}, validate_default=True)


class PipelineRun(BaseModel):
    apiVersion: str | None = Field(
        default=None,
        description='APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources',
    )
    kind: str | None = Field(
        default=None,
        description='Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds',
    )
    metadata: V1ObjectMeta | None = Field(default={}, validate_default=True)
    spec: V1PipelineRunSpec | None = Field(default={}, validate_default=True)
    status: V1PipelineRunStatus | None = Field(default={}, validate_default=True)


class V1Pipeline(BaseModel):
    apiVersion: str | None = Field(
        default=None,
        description='APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources',
    )
    kind: str | None = Field(
        default=None,
        description='Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds',
    )
    metadata: V1ObjectMeta | None = Field(default={}, validate_default=True)
    spec: V1PipelineSpec | None = Field(
        default={},
        description='Spec holds the desired state of the Pipeline from the client',
        validate_default=True,
    )


class V1PipelineList(BaseModel):
    apiVersion: str | None = Field(
        default=None,
        description='APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources',
    )
    items: list[V1Pipeline]
    kind: str | None = Field(
        default=None,
        description='Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds',
    )
    metadata: V1ListMeta | None = Field(default={}, validate_default=True)


class V1PipelineRun(BaseModel):
    apiVersion: str | None = Field(
        default=None,
        description='APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources',
    )
    kind: str | None = Field(
        default=None,
        description='Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds',
    )
    metadata: V1ObjectMeta | None = Field(default={}, validate_default=True)
    spec: V1PipelineRunSpec | None = Field(default={}, validate_default=True)
    status: V1PipelineRunStatus | None = Field(default={}, validate_default=True)


class V1PipelineRunList(BaseModel):
    apiVersion: str | None = Field(
        default=None,
        description='APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources',
    )
    items: list[V1PipelineRun] | None = None
    kind: str | None = Field(
        default=None,
        description='Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds',
    )
    metadata: V1ListMeta | None = Field(default={}, validate_default=True)


class V1PipelineRunSpec(BaseModel):
    managedBy: str | None = Field(
        default=None,
        description='ManagedBy indicates which controller is responsible for reconciling this resource. If unset or set to "tekton.dev/pipeline", the default Tekton controller will manage this resource. This field is immutable.',
    )
    params: list[V1Param] | None = Field(
        default=None, description='Params is a list of parameter names and values.'
    )
    pipelineRef: V1PipelineRef | None = None
    pipelineSpec: V1PipelineSpec | None = Field(
        default=None,
        description='Specifying PipelineSpec can be disabled by setting `disable-inline-spec` feature flag. See Pipeline.spec (API version: tekton.dev/v1)',
    )
    status: str | None = Field(
        default=None,
        description='Used for cancelling a pipelinerun (and maybe more later on)',
    )
    taskRunSpecs: list[V1PipelineTaskRunSpec] | None = Field(
        default=None, description='TaskRunSpecs holds a set of runtime specs'
    )
    taskRunTemplate: V1PipelineTaskRunTemplate | None = Field(
        default={},
        description='TaskRunTemplate represent template of taskrun',
        validate_default=True,
    )
    timeouts: V1TimeoutFields | None = Field(
        default=None,
        description='Time after which the Pipeline times out. Currently three keys are accepted in the map pipeline, tasks and finally with Timeouts.pipeline >= Timeouts.tasks + Timeouts.finally',
    )
    workspaces: list[V1WorkspaceBinding] | None = Field(
        default=None,
        description='Workspaces holds a set of workspace bindings that must match names with those declared in the pipeline.',
    )


class V1PipelineRunStatus(BaseModel):
    annotations: dict[str, str] | None = Field(
        default=None,
        description='Annotations is additional Status fields for the Resource to save some additional State as well as convey more information to the user. This is roughly akin to Annotations on any k8s resource, just the reconciler conveying richer information outwards.',
    )
    childReferences: list[V1ChildStatusReference] | None = Field(
        default=None,
        description='list of TaskRun and Run names, PipelineTask names, and API versions/kinds for children of this PipelineRun.',
    )
    completionTime: V1Time | None = Field(
        default=None,
        description='CompletionTime is the time the PipelineRun completed.',
    )
    conditions: list[KnativeCondition] | None = Field(
        default=None,
        description="Conditions the latest available observations of a resource's current state.",
    )
    finallyStartTime: V1Time | None = Field(
        default=None,
        description='FinallyStartTime is when all non-finally tasks have been completed and only finally tasks are being executed.',
    )
    observedGeneration: int | None = Field(
        default=None,
        description="ObservedGeneration is the 'Generation' of the Service that was last processed by the controller.",
    )
    pipelineSpec: V1PipelineSpec | None = Field(
        default=None,
        description='PipelineSpec contains the exact spec used to instantiate the run. See Pipeline.spec (API version: tekton.dev/v1)',
    )
    provenance: V1Provenance | None = Field(
        default=None,
        description='Provenance contains some key authenticated metadata about how a software artifact was built (what sources, what inputs/outputs, etc.).',
    )
    results: list[V1PipelineRunResult] | None = Field(
        default=None,
        description="Results are the list of results written out by the pipeline task's containers",
    )
    skippedTasks: list[V1SkippedTask] | None = Field(
        default=None,
        description='list of tasks that were skipped due to when expressions evaluating to false',
    )
    spanContext: dict[str, str] | None = Field(
        default=None, description='SpanContext contains tracing span context fields'
    )
    startTime: V1Time | None = Field(
        default=None,
        description='StartTime is the time the PipelineRun is actually started.',
    )


class V1PipelineRunStatusFields(BaseModel):
    childReferences: list[V1ChildStatusReference] | None = Field(
        default=None,
        description='list of TaskRun and Run names, PipelineTask names, and API versions/kinds for children of this PipelineRun.',
    )
    completionTime: V1Time | None = Field(
        default=None,
        description='CompletionTime is the time the PipelineRun completed.',
    )
    finallyStartTime: V1Time | None = Field(
        default=None,
        description='FinallyStartTime is when all non-finally tasks have been completed and only finally tasks are being executed.',
    )
    pipelineSpec: V1PipelineSpec | None = Field(
        default=None,
        description='PipelineSpec contains the exact spec used to instantiate the run. See Pipeline.spec (API version: tekton.dev/v1)',
    )
    provenance: V1Provenance | None = Field(
        default=None,
        description='Provenance contains some key authenticated metadata about how a software artifact was built (what sources, what inputs/outputs, etc.).',
    )
    results: list[V1PipelineRunResult] | None = Field(
        default=None,
        description="Results are the list of results written out by the pipeline task's containers",
    )
    skippedTasks: list[V1SkippedTask] | None = Field(
        default=None,
        description='list of tasks that were skipped due to when expressions evaluating to false',
    )
    spanContext: dict[str, str] | None = Field(
        default=None, description='SpanContext contains tracing span context fields'
    )
    startTime: V1Time | None = Field(
        default=None,
        description='StartTime is the time the PipelineRun is actually started.',
    )


class V1PipelineSpec(BaseModel):
    description: str | None = Field(
        default=None,
        description='Description is a user-facing description of the pipeline that may be used to populate a UI.',
    )
    displayName: str | None = Field(
        default=None,
        description='DisplayName is a user-facing name of the pipeline that may be used to populate a UI.',
    )
    finally_: list[V1PipelineTask] | None = Field(
        default=None,
        alias='finally',
        description='Finally declares the list of Tasks that execute just before leaving the Pipeline i.e. either after all Tasks are finished executing successfully or after a failure which would result in ending the Pipeline',
    )
    params: list[V1ParamSpec] | None = Field(
        default=None,
        description='Params declares a list of input parameters that must be supplied when this Pipeline is run.',
    )
    results: list[V1PipelineResult] | None = Field(
        default=None,
        description='Results are values that this pipeline can output once run',
    )
    tasks: list[V1PipelineTask] | None = Field(
        default=None,
        description='Tasks declares the graph of Tasks that execute when this Pipeline is run.',
    )
    workspaces: list[V1PipelineWorkspaceDeclaration] | None = Field(
        default=None,
        description='Workspaces declares a set of named workspaces that are expected to be provided by a PipelineRun.',
    )


class V1PipelineTask(BaseModel):
    description: str | None = Field(
        default=None,
        description='Description is the description of this task within the context of a Pipeline. This description may be used to populate a UI.',
    )
    displayName: str | None = Field(
        default=None,
        description='DisplayName is the display name of this task within the context of a Pipeline. This display name may be used to populate a UI.',
    )
    matrix: V1Matrix | None = Field(
        default=None,
        description='Matrix declares parameters used to fan out this task.',
    )
    name: str | None = Field(
        default=None,
        description='Name is the name of this task within the context of a Pipeline. Name is used as a coordinate with the `from` and `runAfter` fields to establish the execution order of tasks relative to one another.',
    )
    onError: str | None = Field(
        default=None,
        description='OnError defines the exiting behavior of a PipelineRun on error can be set to [ continue | stopAndFail ]',
    )
    params: list[V1Param] | None = Field(
        default=None, description='Parameters declares parameters passed to this task.'
    )
    pipelineRef: V1PipelineRef | None = Field(
        default=None,
        description='PipelineRef is a reference to a pipeline definition Note: PipelineRef is in preview mode and not yet supported',
    )
    pipelineSpec: V1PipelineSpec | None = Field(
        default=None,
        description='PipelineSpec is a specification of a pipeline Note: PipelineSpec is in preview mode and not yet supported Specifying PipelineSpec can be disabled by setting `disable-inline-spec` feature flag. See Pipeline.spec (API version: tekton.dev/v1)',
    )
    retries: int | None = Field(
        default=None,
        description='Retries represents how many times this task should be retried in case of task failure: ConditionSucceeded set to False',
    )
    runAfter: list[str] | None = Field(
        default=None,
        description='RunAfter is the list of PipelineTask names that should be executed before this Task executes. (Used to force a specific ordering in graph execution.)',
    )
    taskRef: V1TaskRef | None = Field(
        default=None, description='TaskRef is a reference to a task definition.'
    )
    taskSpec: V1EmbeddedTask | None = Field(
        default=None,
        description='TaskSpec is a specification of a task Specifying TaskSpec can be disabled by setting `disable-inline-spec` feature flag. See Task.spec (API version: tekton.dev/v1)',
    )
    timeout: V1Duration | None = Field(
        default=None,
        description="Duration after which the TaskRun times out. Defaults to 1 hour. Refer Go's ParseDuration documentation for expected format: https://golang.org/pkg/time/#ParseDuration",
    )
    when: list[V1WhenExpression] | None = Field(
        default=None,
        description='When is a list of when expressions that need to be true for the task to run',
    )
    workspaces: list[V1WorkspacePipelineTaskBinding] | None = Field(
        default=None,
        description='Workspaces maps workspaces from the pipeline spec to the workspaces declared in the Task.',
    )


V1TaskRunStatus.model_rebuild()
PipelineRun.model_rebuild()
V1Pipeline.model_rebuild()
V1PipelineRun.model_rebuild()
V1PipelineRunSpec.model_rebuild()
V1PipelineRunStatus.model_rebuild()
V1PipelineRunStatusFields.model_rebuild()
V1PipelineSpec.model_rebuild()
