# GENERATED by codegen/generate.py — DO NOT EDIT.
# generated by datamodel-codegen:

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, constr


class QualityGate(BaseModel):
    autotestName: str | None = Field(
        default=None, description='A name of autotests to run with quality gate'
    )
    branchName: str | None = Field(
        default=None, description='A branch name to use from autotests repository'
    )
    qualityGateType: str = Field(
        ..., description='A type of quality gate, e.g. "Manual", "Autotests"'
    )
    stepName: constr(min_length=2) = Field(
        ..., description='Specifies a name of particular'
    )


class Library(BaseModel):
    branch: str | None = Field(
        default=None, description='Branch which should be used for a library'
    )
    name: str | None = Field(default=None, description='A name of a library')


class Source(BaseModel):
    library: Library | None = Field(
        default=None, description='A reference to a non default source library'
    )
    type: str = Field(
        default='default', description='Type of pipeline library, e.g. default, library'
    )


class TriggerType(StrEnum):
    Auto = 'Auto'
    Manual = 'Manual'
    Auto_stable = 'Auto-stable'


class Spec(BaseModel):
    cdPipeline: constr(min_length=2) = Field(
        ..., description='Name of CD pipeline which this Stage will be linked to.'
    )
    cleanTemplate: str | None = Field(
        default=None,
        description='CleanTemplate specifies the name of Tekton TriggerTemplate used for cleanup environment pipeline.',
        examples=['clean'],
    )
    clusterName: str = Field(
        default='in-cluster',
        description='Specifies a name of cluster where the application will be deployed.\nDefault value is "in-cluster" which means that application will be deployed in the same cluster where CD Pipeline is running.',
    )
    description: constr(min_length=0) = Field(
        ..., description='A description of a stage.'
    )
    name: constr(min_length=2) = Field(..., description='Name of a stage.')
    namespace: str = Field(
        ..., description='Namespace where the application will be deployed.'
    )
    order: int = Field(
        ...,
        description='The order to lay out Stages.\nThe order should start from 0, and the next stages should use +1 for the order.',
    )
    qualityGates: list[QualityGate] = Field(
        ..., description='A list of quality gates to be processed'
    )
    source: Source | None = Field(
        default={'type': 'default'},
        description='Specifies a source of a pipeline library which will run release',
        validate_default=True,
    )
    triggerTemplate: str = Field(
        default='deploy',
        description='Specifies a name of Tekton TriggerTemplate used as a blueprint for deployment pipeline.\nDefault value is "deploy" which means that default TriggerTemplate will be used.\nThe default TriggerTemplate is delivered using edp-tekton helm chart.',
    )
    triggerType: TriggerType = Field(
        default=TriggerType.Manual, description='Stage deployment trigger type.'
    )


class Result(StrEnum):
    success = 'success'
    error = 'error'


class Status(BaseModel):
    action: str = Field(..., description='The last Action was performed.')
    available: bool = Field(
        ...,
        description='This flag indicates neither Stage are initialized and ready to work. Defaults to false.',
    )
    detailed_message: str | None = Field(
        default=None,
        description='Detailed information regarding action result\nwhich were performed',
    )
    last_time_updated: AwareDatetime = Field(
        ..., description='Information when  the last time the action were performed.'
    )
    result: Result = Field(
        ...,
        description='A result of an action which were performed.\n- "success": action where performed successfully;\n- "error": error has occurred;',
    )
    shouldBeHandled: bool | None = Field(
        default=None,
        description='Should update of status be handled. Defaults to false.',
    )
    status: str = Field(..., description='Specifies a current status of Stage.')
    username: str = Field(..., description='Name of user who made a last change.')
    value: str = Field(..., description='Specifies a current state of Stage.')


class Stage(BaseModel):
    apiVersion: str | None = Field(
        default=None,
        description='APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources',
    )
    kind: str | None = Field(
        default=None,
        description='Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds',
    )
    metadata: dict[str, Any] | None = None
    spec: Spec = Field(
        ...,
        description='StageSpec defines the desired state of Stage.\nNOTE: for deleting the stage use stages order - delete only the latest stage.',
    )
    status: Status | None = Field(
        default=None, description='StageStatus defines the observed state of Stage.'
    )
