# GENERATED by codegen/generate.py — DO NOT EDIT.
# generated by datamodel-codegen:
#   filename:  tmp2l22pml3.json

from __future__ import annotations

from pydantic import BaseModel


class TriggerTemplate(BaseModel):
    pass
